import Footer from './Shared/Layout/Footer';
import Header from './Shared/Layout/Header';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en">
            <Head>
                <title>Product Listing</title>
                <meta name="description" content="A basic product listing page" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className={inter.className}>
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
